### ISSUE TITLE
tsconfig does not use @sourcegraph/tsconfig

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph-basic-code-intel#131]
This would have avoided problems where for example Rijnard has to figure out a tsconfig setting to make `bind()` work:

https://github.com/sourcegraph/sourcegraph-basic-code-intel/commit/f85756d42d2fc920b1f3d1b9d3cd76db9dd8a22e#diff-32ab45b0a7cbf0aa8200c5670863c486R16

**Comment by efritz** [comment]
Sure does now.
