### ISSUE TITLE
Add support for language-specific definition regexes

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph-basic-code-intel#225]
universal-ctags has built-in support for Clojure, but some definitions are still not found (see https://github.com/sourcegraph/sourcegraph/issues/3614#issuecomment-581636768).

TODO

- [x] See if it's possible to add regexes (like https://github.com/sourcegraph/sourcegraph/tree/master/cmd/symbols/.ctags.d) to a built-in language in universal-ctags
- [ ] If that's not possible, then add a new property `definitionRegex` to https://github.com/sourcegraph/sourcegraph-basic-code-intel/blob/9398fdccb65be32b4248e68fd221e6ee44608cf3/shared/search/handler.ts#L6 which instructs basic-code-intel to do a plain text search when a symbol search returns 0 results.

**Comment by efritz** [comment]
See https://github.com/sourcegraph/sourcegraph/pull/8413

**Comment by efritz** [comment]
If we end up doing configurable regex, we'll add it to the site admin settings so that it can be added to ctags on the fly, not here.
