### ISSUE TITLE
Toggle state is not preserved when going GitHub -> Sourcegraph

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph-basic-code-intel#5]
The Sourcegraph extension API does not let you update *user* settings when the extension is running on GitHub via the browser extension.

Therefore we have the following problem:

1. You are on GitHub and toggle it to show fuzzy code intel
2. You click on "Find references" intending to see fuzzy references for that thing
3. You are taken to Sourcegraph, where you see precise references

Your toggling in step 1 currently has no way to change your user settings on Sourcegraph, only your client settings in the browser extension.

**Comment by chrismwendt** [comment]
The intended behavior is solved by the communication between the browser extension and the Sourcegraph instance https://github.com/sourcegraph/sourcegraph/pull/13107

That doesn't provide the ability to change settings at different configuration levels, but if that becomes a need, let's open a new issue for it.
